
  create table "public"."sales_deals" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "value" integer not null
      );


CREATE UNIQUE INDEX sales_deals_pkey ON public.sales_deals USING btree (id);

alter table "public"."sales_deals" add constraint "sales_deals_pkey" PRIMARY KEY using index "sales_deals_pkey";

grant references on table "public"."sales_deals" to "anon";

grant trigger on table "public"."sales_deals" to "anon";

grant truncate on table "public"."sales_deals" to "anon";

grant references on table "public"."sales_deals" to "authenticated";

grant trigger on table "public"."sales_deals" to "authenticated";

grant truncate on table "public"."sales_deals" to "authenticated";

grant references on table "public"."sales_deals" to "service_role";

grant trigger on table "public"."sales_deals" to "service_role";

grant truncate on table "public"."sales_deals" to "service_role";


